name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'KeyGen-sh.Client/**'
      - 'KeyGen-sh.Client/Models/**'
  pull_request:
    branches:
      - main
    paths:
      - 'KeyGen-sh.Client/**'
      - 'KeyGen-sh.Client/Models/**'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      shell: pwsh
    - name: Build
      run: dotnet build ci.slnf --configuration Release
    - name: Test
      run: dotnet test ci.slnf --configuration Release --no-build --no-restore