name: Build and Test

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
        
  workflow_dispatch:

jobs:
  tstWorkflow:
    runs-on: windows-latest
    
    steps:
    - name: Checkout      
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test ./KeyGen-sh.Client.UnitTest/KeyGen-sh.Client.UnitTest.csproj
